### PR TITLE
Attributed buttons support + swift 4

### PR DESCRIPTION
**Pull request by axmav**
Our designers often want to indent between the letters in the buttons. So I added support for this functionality in your library:
setAttributedText("TEXT FOR STATE", for: .normal)
setAttributedTextColor(.white, for: .normal)
setAttributedTextSpacing(1.2)
setAttribute(NSAttributedStringKey, value: Any, for: .normal)
You can change button text with setAttributedText("ANOTHER TEXT FOR STATE", for: .normal) and all applied attributes refresh automatically.

### CODE REVIEW

**Comment by aloco** [comment]
Thank you, looks like an useful extension - I will look into it when I have more time.

BR

**Comment by aloco** [comment]
@Mazorati do you see any chance to add animated transitions support for state changes with attributed strings like with the other button attributes? (e.g. backgroundColor)

**Comment by axmav** [comment]
@aloco no, i have not...

**Comment by aloco** [comment]
Updated to swift 4.0 including docs etc.
if you need attributed string we should look into how to animate them between state transitions. Till then I will close this one - feel free to reopen it as soon as you find time to dig into it

**Pull request closed without merging**
